<Project>
    <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <!-- Avalonia packages -->
        <!-- Important: keep version in sync! -->
        <PackageVersion Include="Avalonia" Version="12.1.0" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.0" />
        <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.0" />
        <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
        <PackageVersion Include="Avalonia.Desktop" Version="12.1.0" />
        <PackageVersion Include="Avalonia.iOS" Version="12.1.0" />
        <PackageVersion Include="Avalonia.Browser" Version="12.1.0" />
        <PackageVersion Include="Avalonia.Android" Version="12.1.0" />

        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />

        <!-- SukiUI -->
        <PackageVersion Include="SukiUI" Version="7.0.1" />

        <!-- DI & Logging -->
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.10" />
        <PackageVersion Include="NLog" Version="6.1.4" />
        <PackageVersion Include="NLog.Extensions.Logging" Version="6.1.4" />

        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageVersion Include="xunit" Version="2.9.3" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.0" />

        <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.15" />
    </ItemGroup>
</Project>
